### ISSUE TITLE
Duplicate Code of Conduct

### ISSUE THREAD

**Issue by millette** [datproject/awesome-dat#9]
See <https://github.com/datproject/Code-of-Conduct/issues/2>.

**Comment by joehand** [comment]
Oh that was from the original fork of the awesome repo: https://github.com/sindresorhus/awesome/blob/master/code-of-conduct.md

**Comment by millette** [comment]
Thanks for removing [it](https://github.com/datproject/awesome-dat/commit/39d8a13aba375052d7a6d3beda18483913d120df) to avoid confusion.
